"""Add NFC admin notification timestamp

Revision ID: 29c13c9d7c6c
Revises: 43b16dfd5eda
Create Date: 2026-09-20 18:37:16.404614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29c13c9d7c6c'
down_revision = '43b16dfd5eda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nfc_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_notified_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nfc_orders', schema=None) as batch_op:
        batch_op.drop_column('admin_notified_at')

    # ### end Alembic commands ###
