"""Add NFC orders

Revision ID: 43b16dfd5eda
Revises: 001_add_gallery_images
Create Date: 2026-09-20 17:37:50.590193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43b16dfd5eda'
down_revision = '001_add_gallery_images'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nfc_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.String(length=32), nullable=False),
    sa.Column('order_type', sa.String(length=32), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('nfc_price_minor', sa.Integer(), nullable=False),
    sa.Column('discount_minor', sa.Integer(), nullable=False),
    sa.Column('digital_plan', sa.String(length=32), nullable=True),
    sa.Column('digital_plan_price_minor', sa.Integer(), nullable=False),
    sa.Column('total_amount_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('position', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('delivery_location', sa.String(length=255), nullable=False),
    sa.Column('logo_filename', sa.String(length=255), nullable=True),
    sa.Column('design_instructions', sa.Text(), nullable=True),
    sa.Column('replacement_reason', sa.String(length=64), nullable=True),
    sa.Column('payment_reference', sa.String(length=128), nullable=True),
    sa.Column('payment_status', sa.String(length=16), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nfc_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nfc_orders_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_nfc_orders_order_number'), ['order_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_nfc_orders_order_type'), ['order_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_nfc_orders_payment_reference'), ['payment_reference'], unique=True)
        batch_op.create_index(batch_op.f('ix_nfc_orders_payment_status'), ['payment_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_nfc_orders_profile_id'), ['profile_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nfc_orders_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_nfc_orders_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nfc_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nfc_orders_user_id'))
        batch_op.drop_index(batch_op.f('ix_nfc_orders_status'))
        batch_op.drop_index(batch_op.f('ix_nfc_orders_profile_id'))
        batch_op.drop_index(batch_op.f('ix_nfc_orders_payment_status'))
        batch_op.drop_index(batch_op.f('ix_nfc_orders_payment_reference'))
        batch_op.drop_index(batch_op.f('ix_nfc_orders_order_type'))
        batch_op.drop_index(batch_op.f('ix_nfc_orders_order_number'))
        batch_op.drop_index(batch_op.f('ix_nfc_orders_created_at'))

    op.drop_table('nfc_orders')
    # ### end Alembic commands ###
